#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WakeUp.Resource", IsApplication=true)]

namespace WakeUp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLStorage.Resource.String.ApplicationName = global::WakeUp.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::WakeUp.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000d
			public const int BtnAlarm = 2131034125;
			
			// aapt resource value: 0x7f050003
			public const int BtnAlarms = 2131034115;
			
			// aapt resource value: 0x7f05000c
			public const int BtnClean = 2131034124;
			
			// aapt resource value: 0x7f050002
			public const int BtnConfig = 2131034114;
			
			// aapt resource value: 0x7f05000e
			public const int BtnRead = 2131034126;
			
			// aapt resource value: 0x7f050009
			public const int FinishHour = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int GetPositionBtn = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int InitialHour = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int LayoutBtns = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int LayoutConfig = 2131034117;
			
			// aapt resource value: 0x7f050011
			public const int LayoutFirst = 2131034129;
			
			// aapt resource value: 0x7f050000
			public const int LinearLayout01 = 2131034112;
			
			// aapt resource value: 0x7f050012
			public const int TextView02 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int TextView03 = 2131034131;
			
			// aapt resource value: 0x7f05000f
			public const int TxtArchivo = 2131034127;
			
			// aapt resource value: 0x7f050006
			public const int TxtName = 2131034118;
			
			// aapt resource value: 0x7f050010
			public const int TxtPrueba = 2131034128;
			
			// aapt resource value: 0x7f050007
			public const int TxtRemember = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int ViewFlipper01 = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public const int tableRow1 = 2131034122;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
